export const dCity = [];
export const dRegion = [];
export const dOption = [];
export const dList = [
  {
    tourId: 1,
    title: "서울 도심 투어",
    peopleCnt: 10,
    pay: 50000,
    notice: "출발 10분 전에 모여주세요.",
    meetLongitude: "126.9784",
    meetLatitude: "37.5665",
    meetAddress: "서울특별시 중구 세종대로 110",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "김가이드",
  },
  {
    tourId: 2,
    title: "남산 케이블카 투어",
    peopleCnt: 8,
    pay: 40000,
    notice: "산책을 위해 편한 신발을 준비해주세요.",
    meetLongitude: "126.9882",
    meetLatitude: "37.5512",
    meetAddress: "서울특별시 중구 남산공원길 126",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "박가이드",
  },
  {
    tourId: 3,
    title: "경복궁 역사 투어",
    peopleCnt: 12,
    pay: 30000,
    notice: "경복궁 입장권은 포함되어 있지 않습니다.",
    meetLongitude: "126.9769",
    meetLatitude: "37.5796",
    meetAddress: "서울특별시 종로구 사직로 161",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "이가이드",
  },
  {
    tourId: 4,
    title: "한강 자전거 투어",
    peopleCnt: 15,
    pay: 20000,
    notice: "자전거 대여비는 개별 부담입니다.",
    meetLongitude: "126.8772",
    meetLatitude: "37.5255",
    meetAddress: "서울특별시 영등포구 여의도동",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "최가이드",
  },
  {
    tourId: 5,
    title: "북촌 한옥마을 탐방",
    peopleCnt: 10,
    pay: 25000,
    notice: "편안한 옷차림을 권장합니다.",
    meetLongitude: "126.9849",
    meetLatitude: "37.5826",
    meetAddress: "서울특별시 종로구 계동길 37",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "윤가이드",
  },
  {
    tourId: 6,
    title: "명동 맛집 투어",
    peopleCnt: 6,
    pay: 45000,
    notice: "개별 음식값은 투어 비용에 포함되지 않습니다.",
    meetLongitude: "126.9864",
    meetLatitude: "37.5600",
    meetAddress: "서울특별시 중구 명동8길",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "정가이드",
  },
  {
    tourId: 7,
    title: "인사동 전통 문화 체험",
    peopleCnt: 9,
    pay: 35000,
    notice: "전통 공예 체험 비용이 포함되어 있습니다.",
    meetLongitude: "126.9867",
    meetLatitude: "37.5703",
    meetAddress: "서울특별시 종로구 인사동길",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "홍가이드",
  },
  {
    tourId: 8,
    title: "동대문 야시장 투어",
    peopleCnt: 14,
    pay: 20000,
    notice: "현금이나 카드를 준비해 주세요.",
    meetLongitude: "127.0077",
    meetLatitude: "37.5704",
    meetAddress: "서울특별시 종로구 종로 288",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "백가이드",
  },
  {
    tourId: 9,
    title: "잠실 롯데월드 투어",
    peopleCnt: 20,
    pay: 60000,
    notice: "롯데월드 입장권은 개별 구매하셔야 합니다.",
    meetLongitude: "127.1001",
    meetLatitude: "37.5112",
    meetAddress: "서울특별시 송파구 올림픽로 240",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "조가이드",
  },
  {
    tourId: 10,
    title: "이태원 글로벌 푸드 투어",
    peopleCnt: 10,
    pay: 55000,
    notice: "다양한 음식을 맛볼 수 있도록 준비하세요.",
    meetLongitude: "126.9946",
    meetLatitude: "37.5345",
    meetAddress: "서울특별시 용산구 이태원로",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "김가이드",
  },
];
