export const dCity = [
  {
    cityId: 9,
    cityName: "수원시",
    regionId: 9,
  },
  {
    cityId: 10,
    cityName: "고양시",
    regionId: 9,
  },
  {
    cityId: 11,
    cityName: "용인시",
    regionId: 9,
  },
  {
    cityId: 12,
    cityName: "성남시",
    regionId: 9,
  },
  {
    cityId: 13,
    cityName: "부천시",
    regionId: 9,
  },
  {
    cityId: 14,
    cityName: "화성시",
    regionId: 9,
  },
  {
    cityId: 15,
    cityName: "남양주시",
    regionId: 9,
  },
  {
    cityId: 16,
    cityName: "안산시",
    regionId: 9,
  },
  {
    cityId: 17,
    cityName: "안양시",
    regionId: 9,
  },
  {
    cityId: 18,
    cityName: "평택시",
    regionId: 9,
  },
  {
    cityId: 19,
    cityName: "의정부시",
    regionId: 9,
  },
  {
    cityId: 20,
    cityName: "파주시",
    regionId: 9,
  },
  {
    cityId: 21,
    cityName: "시흥시",
    regionId: 9,
  },
  {
    cityId: 22,
    cityName: "김포시",
    regionId: 9,
  },
  {
    cityId: 23,
    cityName: "광명시",
    regionId: 9,
  },
  {
    cityId: 24,
    cityName: "광주시",
    regionId: 9,
  },
  {
    cityId: 25,
    cityName: "군포시",
    regionId: 9,
  },
  {
    cityId: 26,
    cityName: "오산시",
    regionId: 9,
  },
  {
    cityId: 27,
    cityName: "이천시",
    regionId: 9,
  },
  {
    cityId: 28,
    cityName: "하남시",
    regionId: 9,
  },
  {
    cityId: 29,
    cityName: "안성시",
    regionId: 9,
  },
  {
    cityId: 30,
    cityName: "양주시",
    regionId: 9,
  },
  {
    cityId: 31,
    cityName: "구리시",
    regionId: 9,
  },
  {
    cityId: 32,
    cityName: "포천시",
    regionId: 9,
  },
  {
    cityId: 33,
    cityName: "의왕시",
    regionId: 9,
  },
  {
    cityId: 34,
    cityName: "여주시",
    regionId: 9,
  },
  {
    cityId: 35,
    cityName: "동두천시",
    regionId: 9,
  },
  {
    cityId: 36,
    cityName: "과천시",
    regionId: 9,
  },
];
export const dRegion = [
  {
    regionId: 10,
    regionName: "강원도",
  },
  {
    regionId: 9,
    regionName: "경기도",
  },
  {
    regionId: 16,
    regionName: "경상남도",
  },
  {
    regionId: 15,
    regionName: "경상북도",
  },
  {
    regionId: 5,
    regionName: "광주광역시",
  },
  {
    regionId: 3,
    regionName: "대구광역시",
  },
  {
    regionId: 6,
    regionName: "대전광역시",
  },
  {
    regionId: 2,
    regionName: "부산광역시",
  },
  {
    regionId: 1,
    regionName: "서울특별시",
  },
  {
    regionId: 8,
    regionName: "세종특별자치시",
  },
  {
    regionId: 7,
    regionName: "울산광역시",
  },
  {
    regionId: 4,
    regionName: "인천광역시",
  },
  {
    regionId: 14,
    regionName: "전라남도",
  },
  {
    regionId: 13,
    regionName: "전라북도",
  },
  {
    regionId: 17,
    regionName: "제주특별자치도",
  },
  {
    regionId: 12,
    regionName: "충청남도",
  },
  {
    regionId: 11,
    regionName: "충청북도",
  },
];
export const dOption = [
  {
    categoryId: 1,
    categoryName: "차량여부",
    categoryType: "O",
  },
  {
    categoryId: 2,
    categoryName: "외국어 사용가능 여부",
    categoryType: "O",
  },
  {
    categoryId: 3,
    categoryName: "Wi-Fi 가능 여부",
    categoryType: "O",
  },
  {
    categoryId: 4,
    categoryName: "에어컨 유무",
    categoryType: "O",
  },
  {
    categoryId: 5,
    categoryName: "음식 반입 가능 여부",
    categoryType: "O",
  },
  {
    categoryId: 6,
    categoryName: "주차 가능 여부",
    categoryType: "O",
  },
  {
    categoryId: 7,
    categoryName: "장애인 편의시설 유무",
    categoryType: "O",
  },
  {
    categoryId: 8,
    categoryName: "반려동물 동반 가능 여부",
    categoryType: "O",
  },
  {
    categoryId: 9,
    categoryName: "야외 활동 가능 여부",
    categoryType: "O",
  },
  {
    categoryId: 10,
    categoryName: "지정 좌석 여부",
    categoryType: "O",
  },
  {
    categoryId: 11,
    categoryName: "사진 촬영 가능 여부",
    categoryType: "O",
  },
  {
    categoryId: 12,
    categoryName: "음악 제공 여부",
    categoryType: "O",
  },
  {
    categoryId: 13,
    categoryName: "무료 이용 여부",
    categoryType: "O",
  },
  {
    categoryId: 14,
    categoryName: "VIP 서비스 제공 여부",
    categoryType: "O",
  },
  {
    categoryId: 15,
    categoryName: "스포츠 장비 대여 가능 여부",
    categoryType: "O",
  },
  {
    categoryId: 16,
    categoryName: "가이드 포함 여부",
    categoryType: "O",
  },
  {
    categoryId: 17,
    categoryName: "고급 옵션 제공 여부",
    categoryType: "O",
  },
  {
    categoryId: 18,
    categoryName: "현장 결제 가능 여부",
    categoryType: "O",
  },
  {
    categoryId: 19,
    categoryName: "미리 예약 필요 여부",
    categoryType: "O",
  },
  {
    categoryId: 20,
    categoryName: "단체 할인 가능 여부",
    categoryType: "O",
  },
];
export const dList = [
  {
    tourId: 1,
    title: "서울 도심 투어",
    peopleCnt: 10,
    pay: 50000,
    notice: "출발 10분 전에 모여주세요.",
    meetLongitude: "126.9784",
    meetLatitude: "37.5665",
    meetAddress: "서울특별시 중구 세종대로 110",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "김가이드",
  },
  {
    tourId: 2,
    title: "남산 케이블카 투어",
    peopleCnt: 8,
    pay: 40000,
    notice: "산책을 위해 편한 신발을 준비해주세요.",
    meetLongitude: "126.9882",
    meetLatitude: "37.5512",
    meetAddress: "서울특별시 중구 남산공원길 126",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "박가이드",
  },
  {
    tourId: 3,
    title: "경복궁 역사 투어",
    peopleCnt: 12,
    pay: 30000,
    notice: "경복궁 입장권은 포함되어 있지 않습니다.",
    meetLongitude: "126.9769",
    meetLatitude: "37.5796",
    meetAddress: "서울특별시 종로구 사직로 161",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "이가이드",
  },
  {
    tourId: 4,
    title: "한강 자전거 투어",
    peopleCnt: 15,
    pay: 20000,
    notice: "자전거 대여비는 개별 부담입니다.",
    meetLongitude: "126.8772",
    meetLatitude: "37.5255",
    meetAddress: "서울특별시 영등포구 여의도동",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "최가이드",
  },
  {
    tourId: 5,
    title: "북촌 한옥마을 탐방",
    peopleCnt: 10,
    pay: 25000,
    notice: "편안한 옷차림을 권장합니다.",
    meetLongitude: "126.9849",
    meetLatitude: "37.5826",
    meetAddress: "서울특별시 종로구 계동길 37",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "윤가이드",
  },
  {
    tourId: 6,
    title: "명동 맛집 투어",
    peopleCnt: 6,
    pay: 45000,
    notice: "개별 음식값은 투어 비용에 포함되지 않습니다.",
    meetLongitude: "126.9864",
    meetLatitude: "37.5600",
    meetAddress: "서울특별시 중구 명동8길",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "정가이드",
  },
  {
    tourId: 7,
    title: "인사동 전통 문화 체험",
    peopleCnt: 9,
    pay: 35000,
    notice: "전통 공예 체험 비용이 포함되어 있습니다.",
    meetLongitude: "126.9867",
    meetLatitude: "37.5703",
    meetAddress: "서울특별시 종로구 인사동길",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "홍가이드",
  },
  {
    tourId: 8,
    title: "동대문 야시장 투어",
    peopleCnt: 14,
    pay: 20000,
    notice: "현금이나 카드를 준비해 주세요.",
    meetLongitude: "127.0077",
    meetLatitude: "37.5704",
    meetAddress: "서울특별시 종로구 종로 288",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "백가이드",
  },
  {
    tourId: 9,
    title: "잠실 롯데월드 투어",
    peopleCnt: 20,
    pay: 60000,
    notice: "롯데월드 입장권은 개별 구매하셔야 합니다.",
    meetLongitude: "127.1001",
    meetLatitude: "37.5112",
    meetAddress: "서울특별시 송파구 올림픽로 240",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "조가이드",
  },
  {
    tourId: 10,
    title: "이태원 글로벌 푸드 투어",
    peopleCnt: 10,
    pay: 55000,
    notice: "다양한 음식을 맛볼 수 있도록 준비하세요.",
    meetLongitude: "126.9946",
    meetLatitude: "37.5345",
    meetAddress: "서울특별시 용산구 이태원로",
    mainImgUrl: "@/assets/images/default.png",
    guidName: "김가이드",
  },
];
